### ISSUE TITLE
Error compilation 

### ISSUE THREAD

**Issue by yanrising** [kargakis/arbitrage-contracts#1]
$ npx hardhat compile
Solidity 0.8.10 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/reference/solidity-support

Compiling 1 file with 0.8.10
TypeError: Function has override specified but does not override anything.
   --> contracts/FlashLoan.sol:139:9:
    |
139 |         override
    |         ^^^^^^^^

TypeError: Contract "FlashLoan" should be marked as abstract.
  --> contracts/FlashLoan.sol:22:1:
   |
22 | contract FlashLoan is IFlashLoanReceiver, Ownable {
   | ^ (Relevant source part starts here and spans across multiple lines).
Note: Missing implementation: 
 --> contracts/interfaces/IFlashLoanReceiver.sol:5:3:
  |
5 |   function executeOperation(
  |   ^ (Relevant source part starts here and spans across multiple lines).

Error HH600: Compilation failed

For more info go to https://hardhat.org/HH600 or run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Any ideas?

**Comment by kargakis** [comment]
You will need to use Foundry to build this project.

https://getfoundry.sh/
